---
- hosts: '{{ host }}'
  remote_user: '{{ user }}'
  tasks:

    - name: NTP - Add primary server to configuration file
      become: true
      lineinfile:
        path: /etc/ntp.conf
        backup: yes
        state: present
        insertbefore: '^server 0.rhel.pool.ntp.org iburst'
        line: server 10.200.1.220
      tags: ntp

    - name: NTP - Add secondary server to configuration file
      become: true
      lineinfile:
        path: /etc/ntp.conf
        state: present
        insertbefore: '^server 1.rhel.pool.ntp.org iburst'
        line: server 10.200.1.240
      tags: ntp

    - name: NTP - Set timezone to America/Sao_Paulo
      become: true
      timezone:
        name: America/Sao_Paulo

    - name: NTP - Make sure it is stopped
      become: true
      service:
        name: ntpd
        state: stopped
        enabled: yes
      tags: ntp

    - name: NTP - Sync time
      become: true
      shell:
        ntpdate 10.200.1.220
      tags: ntp

    - name: NTP - Make sure service is enabled and started up
      become: true
      service:
        name: ntpd
        state: started
        enabled: yes
      tags: ntp

    - name: System - Set hostname
      become: true
      hostname:
        name: '{{ host }}'
      tags: hostname

    - name: PAM - Set root default password
      become: true
      user:
        name: root
        password: $6$j5hJqhf/$TLo.viaoBh6EmRYbuvUavoeWuqtuKPiN3NsXzMTeYHdu1uw8YoSO31zymB5vPaSx4glpXAYXkcbTzxOJgAFcw.

    - name: SSH - Set authorized key taken from file (ansible)
      authorized_key:
        user: '{{ user }}'
        state: present
        key: "{{ lookup('file', 'keys/id_rsa_ansible.pub') }}"
      tags: ssh

    - name: SSH - Set authorized key taken from file (marcio.pessoa)
      authorized_key:
        user: '{{ user }}'
        state: present
        key: "{{ lookup('file', 'keys/id_rsa_marcio.pessoa.pub') }}"
      tags: ssh

    - name: SSH - Disable check DNS
      replace:
        backup: yes
        path: /etc/ssh/sshd_config
        regexp: '#UseDNS yes'
        replace: 'UseDNS no'
      tags: ssh

    - name: SSH - Apply previous configuration
      become: true
      service:
        name: sshd
        state: restarted
        enabled: yes
      tags: ssh

    - name: RPM - Configure proxy
      become: true
      lineinfile:
        backup: yes
        path: /etc/yum.conf
        state: present
        line: proxy=http://10.113.210.99:3128
      tags: rpm

    - name: RPM - Copy packages required for KVM, libvirt and SNMP
      copy:
        src: Downloads/RHEL_IneoQuest/
        dest: /tmp
      tags: rpm

    - name: RPM - Install required packages
      become: true
      yum:
        name: [
          /tmp/gnutls-dane-3.3.26-9.el7.x86_64.rpm,
          /tmp/gnutls-utils-3.3.26-9.el7.x86_64.rpm,
          /tmp/hivex-1.3.10-6.9.el7.x86_64.rpm,
          /tmp/libguestfs-1.36.10-6.el7.x86_64.rpm,
          /tmp/libvirt-3.9.0-14.el7.x86_64.rpm,
          /tmp/libvirt-client-3.9.0-14.el7.x86_64.rpm,
          /tmp/libvirt-daemon-3.9.0-14.el7.x86_64.rpm,
          /tmp/libvirt-daemon-config-nwfilter-3.9.0-14.el7.x86_64.rpm,
          /tmp/libvirt-daemon-driver-lxc-3.9.0-14.el7.x86_64.rpm,
          /tmp/libvirt-python-3.9.0-1.el7.x86_64.rpm,
          /tmp/net-snmp-5.7.2-32.el7.x86_64.rpm,
          /tmp/net-snmp-agent-libs-5.7.2-32.el7.x86_64.rpm,
          /tmp/perl-hivex-1.3.10-6.9.el7.x86_64.rpm,
          /tmp/python-ipaddr-2.1.11-1.el7.noarch.rpm,
          /tmp/qemu-kvm-tools-1.5.3-156.el7.x86_64.rpm,
          /tmp/scrub-2.5.2-7.el7.x86_64.rpm,
          /tmp/squashfs-tools-4.3-0.21.gitaae0aff4.el7.x86_64.rpm,
          /tmp/supermin5-5.1.19-1.el7.x86_64.rpm,
          /tmp/syslinux-4.05-13.el7.x86_64.rpm,
          /tmp/syslinux-extlinux-4.05-13.el7.x86_64.rpm,
          /tmp/virt-install-1.4.3-3.el7.noarch.rpm,
          /tmp/virt-manager-1.4.3-3.el7.noarch.rpm,
          /tmp/virt-manager-common-1.4.3-3.el7.noarch.rpm
        ]
        state: present
      tags: rpm

    - name: Firewall - Make sure service is disabled and stopped
      become: true
      service:
        name: firewalld
        state: stopped
        enabled: no
      tags: firewall

    - name: SNMP - Configuration
      become: true
      lineinfile:
        path: /etc/snmp/snmpd.conf
        backup: yes
        state: present
        insertbefore: BOF
        line: rocommunity public
      tags: snmp

    - name: SNMP - Make sure service is enabled and started up
      become: true
      service:
        name: snmpd
        state: restarted
        enabled: yes
      tags: snmp

    - name: KVM - Create work directory if it does not exist
      become: true
      file:
        path: /home/VM
        state: directory
        mode: '0755'
      tags: kvm

    - name: System - Reboot
      reboot:
        reboot_timeout: 300
