---
- hosts: '{{ host }}'
  remote_user: '{{ user }}'
  tasks:

    - name: PAM - Set sysadm default password
      become: true
      user:
        name: sysadm
        password: $6$j5hJqhf/$TLo.viaoBh6EmRYbuvUavoeWuqtuKPiN3NsXzMTeYHdu1uw8YoSO31zymB5vPaSx4glpXAYXkcbTzxOJgAFcw.

    - name: PAM - Set root default password
      become: true
      user:
        name: root
        password: $6$j5hJqhf/$TLo.viaoBh6EmRYbuvUavoeWuqtuKPiN3NsXzMTeYHdu1uw8YoSO31zymB5vPaSx4glpXAYXkcbTzxOJgAFcw.
