---
- hosts: all
  tasks:

  - name: SSH - Set authorized key taken from file (marcio.pessoa)
    authorized_key:
      user: sysadm
      state: present
      key: "{{ lookup('file', 'keys/id_rsa_marcio.pessoa.pub') }}"
    tags: marcio.pessoa
