---
- hosts: all
  tasks:

    - name: APT - Copy Elastic GPG key
      copy:
        src: keys/GPG-KEY-elasticsearch
        dest: /tmp/GPG-KEY-elasticsearch
      tags: repository, elasticsearch, logstash, kibana, beats, filebeat, metricbeat

    - name: APT - Add Elastic signing key to keyring
      become: true
      apt_key:
        id: D27D666CD88E42B4
        file: /tmp/GPG-KEY-elasticsearch
        state: present
      tags: repository, elasticsearch, logstash, kibana, beats, filebeat, metricbeat

    - name: APT - Add Elastic repository
      become: true
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
      tags: repository, elasticsearch, logstash, kibana, beats, filebeat, metricbeat

    - name: APT - Update repository
      become: true
      apt:
        update_cache: yes
      tags: repository, elasticsearch, logstash, kibana, beats, filebeat, metricbeat

    - name: Elasticsearch - Install
      become: true
      apt:
        name: elasticsearch
        state: present
      tags: elasticsearch

    - name: Elasticsearch - Make sure service is enabled and started up
      become: true
      service:
        name: elasticsearch
        state: started
        enabled: yes
      tags: elasticsearch

    - name: Logstash - Install
      become: true
      apt:
        name: logstash
        state: present
      tags: logstash

    - name: Logstash - Make sure service is enabled and started up
      become: true
      service:
        name: logstash
        state: started
        enabled: yes
      tags: logstash

    - name: Kibana - Install
      become: true
      apt:
        name: kibana
        state: present
      tags: kibana

    - name: Kibana - Make sure service is enabled and started up
      become: true
      service:
        name: kibana
        state: started
        enabled: yes
      tags: kibana

    - name: Filebeat - Install
      become: true
      apt:
        name: filebeat
        state: present
      tags: beats, filebeat, filebeat-elasticsearch, filebeat-logstash

    - name: Filebeat - Configure Elasticsearch hosts
      become: true
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        backup: yes
        state: present
        regexp: '  hosts: \["localhost:9200"\]'
        line: '  hosts: ["10.113.210.40:9200", "10.113.210.8:9200", "10.113.210.9:9200", "10.113.210.10:9200"]'
      tags: beats, filebeat, filebeat-elasticsearch, filebeat-logstash

    - name: Filebeat - Enable System module
      become: true
      shell:
        filebeat modules enable system
      tags: beats, filebeat

    - name: Filebeat - Enable Logstash module
      become: true
      shell:
        filebeat modules enable logstash
      tags: filebeat-logstash

    - name: Filebeat - Make sure service is enabled and started up
      become: true
      service:
        name: filebeat
        state: started
        enabled: yes
      tags: beats, filebeat, filebeat-elasticsearch, filebeat-logstash

    - name: Metricbeat - Install
      become: true
      apt:
        name: metricbeat
        state: present
      tags: beats, metricbeat

    - name: Metricbeat - Configure with Elasticsearch hosts
      become: true
      lineinfile:
        path: /etc/metricbeat/metricbeat.yml
        backup: yes
        state: present
        regexp: '  hosts: \["localhost:9200"\]'
        line: '  hosts: ["10.113.210.40:9200", "10.113.210.8:9200", "10.113.210.9:9200", "10.113.210.10:9200"]'
      tags: beats, metricbeat

    - name: Metricbeat - Enable system module
      become: true
      shell:
        metricbeat modules enable system
      tags: beats, metricbeat

    - name: Metricbeat - Enable memcached module
      become: true
      shell:
        metricbeat modules enable memcached
      tags: beats, metricbeat

    - name: Metricbeat - Enable etcd module
      become: true
      shell:
        metricbeat modules enable etcd
      tags: beats, metricbeat

    - name: Metricbeat - Make sure service is enabled and started up
      become: true
      service:
        name: metricbeat
        state: started
        enabled: yes
      tags: beats, metricbeat

    - name: Heartbeat - Install
      become: true
      apt:
        name: heartbeat-elastic
        state: present
      tags: heartbeat

    - name: Heartbeat - Configure with Elasticsearch hosts
      become: true
      lineinfile:
        path: /etc/heartbeat/heartbeat.yml
        backup: yes
        state: present
        regexp: '  hosts: \["localhost:9200"\]'
        line: '  hosts: ["http://172.16.9.3:9200", "http://172.16.9.4:9200", "http://172.16.9.5:9200", "http://172.16.9.6:9200"]'
      tags: heartbeat

    - name: Heartbeat - Make sure service is enabled and started up
      become: true
      service:
        name: heartbeat-elastic
        state: started
        enabled: yes
      tags: heartbeat
