---
- hosts: '{{ host }}'
  remote_user: '{{ user }}'
  tasks:

    - name: KVM - Install QEMU, KVM, libvirt and bridge-utils
      become: true
      apt:
        package: [
          qemu-kvm,
          libvirt-daemon-system,
          libvirt-clients,
          bridge-utils
        ]
        state: present
        cache_valid_time: 3600
        update_cache: yes
      tags: install
