---
- hosts: all
  tasks:

    - name: APT - Add Zabbix repository
      copy:
        src: Downloads/ansible/zabbix-release_4.0-2+bionic_all.deb
        dest: /tmp/zabbix-release_4.0-2+bionic_all.deb
      tags: zabbix-agent

    - name: APT - Configure Zabbix repository
      become: true
      apt:
        deb: '{{ item }}'
        state: present
      with_items:
        - /tmp/zabbix-release_4.0-2+bionic_all.deb
      tags: zabbix-agent

    - name: Zabbix Agent - Install
      become: true
      apt:
        name: ['zabbix-agent']
        state: present
      tags: zabbix-agent

    - name: Zabbix Agent - Configure
      become: true
      lineinfile:
        dest: /etc/zabbix/zabbix_agentd.conf
        regexp: "^Server="
        insertafter: "^Server="
        line: '{{ item }}'
        state: present
        backup: yes
        backrefs: yes
      with_items:
        - 'Server=127.0.0.1,10.113.210.105,10.113.210.111,10.113.210.112'
      tags: zabbix-agent

    - name: Zabbix - Make sure service is enabled and started up
      become: true
      service:
        name: zabbix-agent
        enabled: yes
        state: restarted
      tags: zabbix-agent
